name 'iap-auth'
maintainer 'GO-JEK Developers'
maintainer_email 'foss+farm@go-jek.com'
license 'All Rights Reserved'
description 'Installs/Configures iap-auth'
long_description 'Installs/Configures iap-auth'
version '0.1.0'
chef_version '>= 12.0'
